In [1]:
#import matplotlib.pyplot as plt
#import numpy as np
%run script/regressor.py

In [2]:
import yfinance as yf

msft = yf.Ticker("MSFT")
hist = msft.history(period="max")
test1 = list(hist['High'])

In [3]:
row = [0.21947749,  0.32948997,  0.81560036,  0.440956  , -0.0606303]

In [4]:
test = Regressor(test1, 5, 2)

In [5]:
first, second, third = test.forecast(row)

In [6]:
first

array([[0.30020667, 0.30668528]])

In [7]:
second

array([[0.09498154, 0.09607952]])

In [8]:
third

array([[0.17425502, 0.17961072]])