In [105]:
%run script/regressor.py

In [106]:
import yfinance as yf

msft = yf.Ticker("MSFT")
hist = msft.history(period="max")
test1 = list(hist['High'])

In [107]:
row = [0.21947749,  0.32948997,  0.81560036,  0.440956  , -0.0606303]

In [108]:
test = Regressor(test1, 5, 2, False)

In [109]:
test.get_sequences()[0]

[[0.06423623578187501,
  0.06478520522557112,
  0.0653341945284124,
  0.06533418838215264,
  0.06368659400218393],
 [0.06478520522557112,
  0.0653341945284124,
  0.06533418838215264,
  0.06368659400218393,
  0.062039636005481034],
 [0.0653341945284124,
  0.06533418838215264,
  0.06368659400218393,
  0.062039636005481034,
  0.061490611038842714],
 [0.06533418838215264,
  0.06368659400218393,
  0.062039636005481034,
  0.061490611038842714,
  0.058745685568408534],
 [0.06368659400218393,
  0.062039636005481034,
  0.061490611038842714,
  0.058745685568408534,
  0.05819671228528023],
 [0.062039636005481034,
  0.061490611038842714,
  0.058745685568408534,
  0.05819671228528023,
  0.06039268663502311],
 [0.061490611038842714,
  0.058745685568408534,
  0.05819671228528023,
  0.06039268663502311,
  0.060941629111766815],
 [0.058745685568408534,
  0.05819671228528023,
  0.06039268663502311,
  0.060941629111766815,
  0.060941656407223786],
 [0.05819671228528023,
  0.06039268663502311,
  0.0609416

In [110]:
first, second, third = test.forecast(row)

ValueError: Expected 2D array, got 1D array instead:
array=[ 0.21947749  0.32948997  0.81560036  0.440956   -0.0606303 ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [102]:
first

array([[0.30020668, 0.30668526]])

In [103]:
second

array([[0.0960795 , 0.09443254]])

In [104]:
third

array([[0.17878446, 0.18408803]])

In [20]:
from sklearn.preprocessing import StandardScaler

In [42]:
test1

[[0.06423625134837865,
  0.06478520522557112,
  0.0653341945284124,
  0.06533419609194284,
  0.06368660929892701],
 [0.06478520522557112,
  0.0653341945284124,
  0.06533419609194284,
  0.06368660929892701,
  0.06203963217859828],
 [0.0653341945284124,
  0.06533419609194284,
  0.06368660929892701,
  0.06203963217859828,
  0.06149063443499105],
 [0.06533419609194284,
  0.06368660929892701,
  0.06203963217859828,
  0.06149063443499105,
  0.058745685568408534],
 [0.06368660929892701,
  0.06203963217859828,
  0.06149063443499105,
  0.058745685568408534,
  0.058196716010570526],
 [0.06203963217859828,
  0.06149063443499105,
  0.058745685568408534,
  0.058196716010570526,
  0.06039264904037201],
 [0.06149063443499105,
  0.058745685568408534,
  0.058196716010570526,
  0.06039264904037201,
  0.0609416589140892],
 [0.058745685568408534,
  0.058196716010570526,
  0.06039264904037201,
  0.0609416589140892,
  0.06094165264806934],
 [0.058196716010570526,
  0.06039264904037201,
  0.0609416589140892,

In [43]:
scaler = StandardScaler().fit(test1)

In [44]:
X_train_scaled = scaler.transform(test1)

In [46]:
X_train_scaled

array([[-0.63242911, -0.63211438, -0.63181055, -0.6315051 , -0.63116436],
       [-0.63241869, -0.63210399, -0.63181055, -0.6315362 , -0.6311954 ],
       [-0.63240828, -0.63210399, -0.6318417 , -0.63156729, -0.63120575],
       ...,
       [ 5.23202316,  5.2309966 ,  5.24748215,  5.24015475,  5.19885407],
       [ 5.23960936,  5.25599108,  5.2488058 ,  5.20825014,  5.25539465],
       [ 5.26464185,  5.25731671,  5.21685252,  5.26488545,  5.51359688]])

In [47]:
X_train_scaled1 = scaler.transform([row])

In [48]:
X_train_scaled1

array([[-0.62948506, -0.62710206, -0.61762509, -0.62441394, -0.63350734]])